---

# nom de la base de données
mediawiki_db_name: "mediawiki"

# nom de l’utilisateur de la base de données et son mot de passe
mediawiki_db_user: "keyproco"
mediawiki_db_password: "keyproco"
# nom et mot de passe de l’administrateur Mediawiki
mediawiki_admin_user: "keyproco"
mediawiki_admin_password: "keyproco"

# nom du Mediawiki et son titre
mediawiki_name: "mediawiki"
mediawiki_title: "KEYPROCO"

# l’emplacement du répertoire d'installation de Mediawiki
mediawiki_directory: "/var/www/html/{{mediawiki_name}}"

# répertoire de maintenance de Mediawiki
mediawiki_maintenance_directory: "{{mediawiki_directory}}/maintenance"

# Definie le premier node du groupe mariadb
mediawiki_db_host: "{{groups.db.0}}"

# l’url des sources Mediawiki
mediawiki_archive_url: "https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz"
